const mongoose=require("mongoose");
const UserSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    username:{
        type:String,
        required:true,
        unique:true
    },
    password:{
        type:String,
        required:true
    },
    email:{
     type:String,
     required:true,
     unique:true
    },
    Gender:String,
    collage:{
        type:String,
        required:true
    },
    desc:String,
    profilePicture:{
        type:String,
        default:"https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png"
    },
    following:{
        type:Array,
        default:[]
    },
    followers:{
      type:Array,
      default:[]
    },
    communities:{
        type:Array,
        default:[]
    },
    Adminof:{
      type:Array,
      default:[]  
    },
    savedposts:{
        type:Array,
        default:[]
    },
    createdpost:{
        type:Array,
        default:[]
    }
},{timestamps:true})
module.exports=mongoose.model("User",UserSchema);